################################### METADATA ###################################

# Contributors: roadelou
# Contacts: 
# Creation Date: 2021-11-14
# Language: Makefile
# Make version: GNU Make 4.3

################################### ALIASES ####################################

# Defining all of the local headers.
TEST_INTEGER_HEAD = $(TEST_HEAD_DIR)/test_integer.h
TEST_STRING_HEAD = $(TEST_HEAD_DIR)/test_string.h
TEST_HEADER_HEAD = $(TEST_HEAD_DIR)/test_header.h

################################### SPECIAL ####################################

# The special rule modifiers (.PHONY etc...) go here

#################################### RULES #####################################

# The rules for your Makefile go here

##################################### EOF ######################################
