################################### METADATA ###################################

# Contributors: roadelou
# Contacts: 
# Creation Date: 2021-11-13
# Language: Makefile
# Make version: GNU Make 4.3

################################### ALIASES ####################################

# Defining all of the local headers.
UTIL_BASE_HEAD = $(UTIL_HEAD_DIR)/base.h
UTIL_DATE_NOW_HEAD = $(UTIL_HEAD_DIR)/date_now.h
UTIL_LIST_HEAD = $(UTIL_HEAD_DIR)/list.h
UTIL_LOG_HEAD = $(UTIL_HEAD_DIR)/log.h

################################### SPECIAL ####################################

# The special rule modifiers (.PHONY etc...) go here

#################################### RULES #####################################

# The rules for your Makefile go here

##################################### EOF ######################################
