################################### METADATA ###################################

# Contributors: roadelou
# Contacts: 
# Creation Date: 2021-11-13
# Language: Makefile
# Make version: GNU Make 4.3

################################### ALIASES ####################################

# Defining all of the local headers.
FORMAT_DYNAMIC_FORMAT_HEAD = $(FORMAT_HEAD_DIR)/dynamic_format.h
FORMAT_SAFE_FORMAT_HEAD = $(FORMAT_HEAD_DIR)/safe_format.h

################################### SPECIAL ####################################

# The special rule modifiers (.PHONY etc...) go here

#################################### RULES #####################################

# The rules for your Makefile go here

##################################### EOF ######################################
