################################### METADATA ###################################

# Contributors: roadelou
# Contacts: 
# Creation Date: 2021-11-13
# Language: Makefile
# Make version: GNU Make 4.3

################################### ALIASES ####################################

# Defining all of the local headers.
EXTENSION_EXTENSION_MATCH_HEAD = $(EXTENSION_HEAD_DIR)/extension_match.h
EXTENSION_FORMAT_EXTENSION_HEAD = $(EXTENSION_HEAD_DIR)/format_extension.h
EXTENSION_GET_EXTENSION_HEAD = $(EXTENSION_HEAD_DIR)/get_extension.h
EXTENSION_GET_FORMAT_EXTENSION_HEAD = $(EXTENSION_HEAD_DIR)/get_format_extension.h

################################### SPECIAL ####################################

# The special rule modifiers (.PHONY etc...) go here

#################################### RULES #####################################

# The rules for your Makefile go here

##################################### EOF ######################################
