################################### METADATA ###################################

# Contributors: roadelou
# Contacts: 
# Creation Date: 2021-11-13
# Language: Makefile
# Make version: GNU Make 4.3

################################### ALIASES ####################################

# The global library header.
TEMPLATE_LIB_HEAD = $(HEAD_DIR)/template.h

# We source the next Makefile.
include $(HEAD_DIR)/template/Makefile

################################### SPECIAL ####################################

# The special rule modifiers (.PHONY etc...) go here

#################################### RULES #####################################

# The rules for your Makefile go here

##################################### EOF ######################################
