################################### METADATA ###################################

# Contributors: roadelou
# Contacts: 
# Creation Date: 2021-11-13
# Language: Makefile
# Make version: GNU Make 4.3

################################### ALIASES ####################################

# The global library header.
TEMPLATE_LIB_HEAD = $(HEAD_DIR)/template.h
#
# The folder where the internal header files are located.
TEMPLATE_LIB_INC = $(HEAD_DIR)/template

EXTENSION_HEAD = $(wildcard $(TEMPLATE_LIB_INC)/test/*.h) $(TEMPLATE_LIB_INC)/test.h
FORMAT_HEAD = $(wildcard $(TEMPLATE_LIB_INC)/format/*.h) $(TEMPLATE_LIB_INC)/format.h
TEST_HEAD = $(wildcard $(TEMPLATE_LIB_INC)/test/*.h) $(TEMPLATE_LIB_INC)/test.h
UTIL_HEAD = $(wildcard $(TEMPLATE_LIB_INC)/util/*.h) $(TEMPLATE_LIB_INC)/util.h

################################### SPECIAL ####################################

# The special rule modifiers (.PHONY etc...) go here

#################################### RULES #####################################

# The rules for your Makefile go here

##################################### EOF ######################################
